name: Build darwin binaries
on:
  push:
    branches: [ main ]
  
permissions:
  contents: write
  statuses: write
  id-token: write # This is required for requesting the JWT/OIDC

jobs:
  build-on-macos:
    name: Build on ${{matrix.runsonimage}}
    runs-on: ${{matrix.runsonimage}}
    strategy:
      matrix:
        include:
          - runsonimage: macos-13
            s3_path: darwin/x86
            display_name: "macOS Intel (x86_64)"
          - runsonimage: macos-14
            s3_path: darwin/aarch64
            display_name: "macOS Apple Silicon (M1)"
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Install gnu-sed as sed
        run: |
          brew install gnu-sed
          PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
        with:
          cache:true
      - name: Build Project
        run: |
          echo "Building on ${{ matrix.display_name }}"
          make release
          make test-certs
          make test
          ls -la build/bin
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: arn:aws:iam::019601885680:role/s3fullaccessgithubrole
          role-session-name: githubmscosintelbuild
          aws-region: us-west-2
      - name: Upload to S3
        id: s3
        run: |
          S3_DESTINATION="s3://creds-helper-intermediate-bucket-for-deployment"
          aws s3 cp build/bin/aws_signing_helper "${S3_DESTINATION}/${{ matrix.s3_path }}/aws_signing_helper"