name: Build darwin binaries
on:
  push:
    branches: [ main ]

jobs:
  Run-on-macos-intel:
    name: Run on macos intel
    runs-on: macos-13
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Project
        run: |
          make release
          ls -la build/bin
      